services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: phong
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lb4_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: phong
      DB_PASSWORD: 123456
      DB_DATABASE: ecommerce
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
