services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: phong
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
